- src/pages/07/m7s/_components/PowerSlam.astro
- src/pages/07/m7s/p2.astro
> Add m7s p2 PowerSlam mechnaism

- src/pages/07/m7s/_components/BrutalImpactActivate.astro
- src/pages/07/m7s/_components/BrutalImpactCast.astro
- src/pages/07/m7s/_mechanics/BrutalImpact.astro
- src/pages/07/m7s/p1.astro
- src/pages/07/m7s/p3.astro
> 增加了p1p3的野蛮碎击

- src/pages/07/m7s/_components/BrutishSwingActivate.astro
- src/pages/07/m7s/_components/BrutishSwingCast.astro
- src/pages/07/m7s/_components/BrutishSwingMoveActivate.astro
- src/pages/07/m7s/_components/ElectrogeneticForceActivate.astro
- src/pages/07/m7s/_components/GlowerPowerCast.astro
- src/pages/07/m7s/_components/RevengeOfTheVinesCast.astro
- src/pages/07/m7s/_mechanics/SBGR.astro
- src/pages/07/m7s/p2.astro
完成P2组合机制
[Stoneringer + Brutish Swing + Glower Power + Revenge of the Vines](https://github.com/mogworks/xivstrat/issues/19) 框架部分
> Feat: complete SBGRFrame

- .prettierrc
- .vscode/settings.json
- eslint.config.mts
> Fix: 修正formatter会错误将html格式化为单引号的问题

- src/components/StratAside.vue
> 修改侧边栏样式：调换阶段、机制排列顺序

- src/pages/07/m8s1/_components/RavenousSaberCast.astro
- src/pages/07/m8s1/p2.astro
> 加入了小怪后的aoe

- src/components/typography/Skill.astro
> Feature: 添加Skill组件，用于显示单个/多个技能名

- src/components/DeveloperCard.astro
- src/components/section/MultiSolutionSection.vue
#65 
原因是发现就算link没填url字段，依旧会href过去
> perf: 若developer.link不是合规的url，则不创建href属性; 解法切换器添加切换动画

- src/pages/07/m8s1/_mechanics/BeckonMoonlight.astro
- src/pages/07/m8s1/_mechanics/ShadowChase.astro
- src/pages/07/m8s1/_mechanics/TerrestrialRage.astro
- src/pages/07/m8s1/_mechanics/TrackingTremors.astro
- src/pages/07/m8s1/_mechanics/WealOfStone.astro
- src/pages/07/m8s1/p3.astro
rt
主要是用<T><P><Skill>代替了一些原来的写法
可读性会好一些
顺带修正了一个排版错误：[
](url)
> Fix: 修正m8s1/p3的一些排版问题 用新组件替换老组件

- src/pages/07/m7s/_mechanics/DDAB.astro
- src/pages/07/m7s/_mechanics/Explosion.astro
- src/pages/07/m7s/_mechanics/NeoBombarianSpecial.astro
- src/pages/07/m7s/_mechanics/PulpSmash.astro
- src/pages/07/m7s/_mechanics/SBGR.astro
- src/pages/07/m7s/_mechanics/SinisterSeeds.astro
- src/pages/07/m7s/_mechanics/SinisterSeedsP3.astro
- src/pages/07/m7s/_mechanics/Sporesplosion.astro
- src/pages/07/m7s/_mechanics/Stoneringer.astro
- src/pages/07/m7s/_mechanics/Stoneringer2First.astro
- src/pages/07/m7s/_mechanics/Stoneringer2Second.astro
- src/pages/07/m7s/_mechanics/StrangeSeeds.astro
- src/pages/07/m7s/_mechanics/TDAB.astro
- 颜色：在已有参数中使用yellow；dark下yellow和amber不错，light下orange表现强，如果修改可以参考。
- 同时把以前的多图换成`<ImgRow>`，单图保留`<Image>`
> feat/m7s: 删除p1p2的border，修改p3和实战图border颜色

- src/components/CollapsibleBox.vue
- src/components/ReferenceItem.astro
1. 为Collapsible组件添加了折叠展开动画，动画持续时间暂设置为0.1s
2. 修复了ReferenceItem标题换行时高度溢出的bug
> Feature && Fix: 副本首页Collapsible组件

- src/layouts/DutyHomeLayout.astro
- src/layouts/DutyLayout.astro
- src/layouts/DutyStratLayout.astro
- src/layouts/Layout.astro
- src/pages/07/m5s/p1.astro
- src/pages/07/m5s/p2.astro
- src/pages/07/m5s/p3.astro
- src/pages/07/m6s/p1.astro
- src/pages/07/m6s/p2.astro
- src/pages/07/m6s/p3.astro
- src/pages/07/m6s/p4.astro
- src/pages/07/m6s/p5.astro
- src/pages/07/m7s/p1.astro
- src/pages/07/m7s/p2.astro
- src/pages/07/m7s/p3.astro
- src/pages/07/m8s1/p1.astro
- src/pages/07/m8s1/p2.astro
- src/pages/07/m8s1/p3.astro
- src/pages/07/m8s2/p1.astro
- src/pages/07/m8s2/p2.astro
- src/pages/07/m8s2/p3.astro
- src/pages/07/m8s2/p4.astro
- src/pages/07/zelenia/p1.astro
- src/pages/07/zelenia/p2.astro
- src/pages/07/zelenia/p3.astro
- src/pages/404.astro
- src/pages/about.astro
1. 除网站首页外增加通用后缀 ` - XivStrat`
2. 副本攻略在通用后缀前增加后缀 ` - 首页/P${phase}`
Close #178
> feat: 调整每一个页面的 Tab Title

- src/components/Macro.astro
- src/layouts/DutyLayout.astro
- src/layouts/Layout.astro
- src/pages/07/m5s/_data/macro.ts
- src/pages/07/m5s/_data/thanks.ts
- src/pages/07/m5s/index.astro
- src/pages/07/m6s/_data/macro.ts
- src/pages/07/m6s/index.astro
1. 修复m5s/m6s宏在游戏内的格式展示
2. 优化样式
3. 增加以默语复制
4. 分割M6S的宏，方便复制
> fix: 修复m5s/m6s宏在游戏内的展示 & 优化样式

- src/components/ResizableImageDialog.vue
- src/pages/07/m6s/index.astro
1. 在handleReset内增加了居中图片功能；
2. m6s两张小抄现在分别使用两个ResizableImageDialog组件，实现点击任意一张图片仅预览该图片的效果。
> Feature: ResizableImageDialog组件图片预览默认居中

- src/components/action/LimitBreak.astro
- src/pages/07/m5s/index.astro
- src/pages/07/m6s/_components/SoulSugarTable.astro
- src/pages/07/m6s/_components/UnlimitedCravingActivate.astro
- src/pages/07/m6s/_data/macro.ts
- src/pages/07/m6s/_mechanics/SoulSugar.astro
- src/pages/07/m6s/index.astro
- src/pages/07/m7s/index.astro
- src/pages/07/m8s1/index.astro
- src/pages/07/m8s2/index.astro
- src/pages/07/zelenia/_mechanics/RoseBloodBloom_6.astro
- src/pages/07/zelenia/index.astro
1. 使用LB组件替换LB文字描述
2. 添加宏标题
3. 修改部分繁中->简中
> fix: 使用LB组件替换LB文字描述等

- src/components/DamageInfo.astro
- src/components/StratSettings.vue
- src/lib/utils.ts
- src/stores/stratSettings.ts
1.  提供伤害值格式设置入口
2. 增加数字分隔符
Close #198
> feat: 提供伤害值格式设置入口并增加数字分隔符

- src/data/duties/07/zelenia.json
- src/pages/07/zelenia/_mechanics/BlessedBarricade.astro
- src/pages/07/zelenia/_translations/cn.ts
- src/pages/07/zelenia/p2.astro
极神P2描述修改
fix:
https://github.com/mogworks/xivstrat/issues/211#issuecomment-2999146756
> feat: 极神P2描述修改

- src/components/navigator/NavItem.vue
- src/components/navigator/Navigation.vue
- src/components/navigator/type.ts
- src/content.config.ts
- src/data/duties/07/fru.json
- src/data/duties/07/m5s.json
- src/data/duties/07/m6s.json
- src/data/duties/07/m7s.json
- src/data/duties/07/m8s1.json
- src/data/duties/07/m8s2.json
- src/data/duties/07/zelenia.json
- src/data/duty.d.ts
- src/layouts/Layout.astro
- src/lib/utils.ts
1. 添加导航信息元数据，使导航通过内容集合生成
2. 导航根据 indexAvailable 进行展示
Fix #212
> feat: 添加导航信息元数据 & 导航根据 indexAvailable 进行展示

- src/components/FooterPagination.astro
- src/components/section/CollapseSection.astro
- src/layouts/DutyHomeLayout.astro
- src/layouts/DutyStratLayout.astro
1. 添加FooterPagination组件，已经在首页和攻略页面适配了导航
2. 修复了CollapseSection组件折叠的时候details部分没有正确隐藏的问题，之前只设置了`max-height: 0`，没有设置`display: none`
> Feature & Fix：FooterPagination和CollapseSection组件

- src/data/duties/07/necron.json
- src/pages/07/necron/index.astro
- src/pages/07/necron/p1.astro
feat: create index page for necron
> Necron index page
